debug: false

vault:
  enabled: true
  price: 1
  # The math expression will be newLevel * levelUp
  # For example if you set to 100 the levelUp price to level 5 will be 500
  levelUp: 100

# Material list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Mutation schema: PLACEABLE -> PLACED
# You can view the placed item watching seeds in debug option(F3) [https://i.gyazo.com/c43c169949b862a934ae11ef9eb64489.png]
items:
  WHEAT: "WHEAT"
  POTATO: "POTATOES"
  CARROT: "CARROTS"
  IRON_ORE: "IRON_ORE"

# Time in seconds of each task
tasks:
  grow: 5
  collect: 10